server:
  port: 8080
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  rowBoundsWithCount: true
  reasonable: false
  params: count=countSql
  page-size-zero: true
  support-methods-arguments: true
feign:
  httpclient:
    enabled: true
